tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed-variant": "#1a5200",
              "on-primary-fixed": "#0b1d2d",
              "error-container": "#ffdad6",
              "on-primary": "#ffffff",
              "primary-fixed": "#d2e4fb",
              "on-surface": "#0b1c30",
              "outline": "#74777d",
              "inverse-primary": "#b7c8de",
              "secondary-container": "#abf288",
              "tertiary": "#0b1811",
              "surface": "#f8f9ff",
              "tertiary-fixed": "#d7e6dc",
              "tertiary-fixed-dim": "#bbcac0",
              "outline-variant": "#c4c6cd",
              "secondary-fixed-dim": "#93d872",
              "on-primary-container": "#8192a7",
              "secondary": "#2d6c11",
              "surface-container-highest": "#d3e4fe",
              "primary": "#041627",
              "on-tertiary-fixed": "#121e18",
              "primary-fixed-dim": "#b7c8de",
              "surface-container-low": "#eff4ff",
              "surface-variant": "#d3e4fe",
              "on-error": "#ffffff",
              "inverse-on-surface": "#eaf1ff",
              "surface-tint": "#4f6073",
              "background": "#f8f9ff",
              "surface-dim": "#cbdbf5",
              "surface-bright": "#f8f9ff",
              "on-tertiary": "#ffffff",
              "tertiary-container": "#1f2c25",
              "on-tertiary-fixed-variant": "#3c4a42",
              "on-surface-variant": "#44474c",
              "primary-container": "#1a2b3c",
              "error": "#ba1a1a",
              "on-secondary-fixed": "#062100",
              "on-error-container": "#93000a",
              "secondary-fixed": "#aef58b",
              "surface-container-high": "#dce9ff",
              "on-secondary": "#ffffff",
              "surface-container": "#e5eeff",
              "inverse-surface": "#213145",
              "on-primary-fixed-variant": "#38485a",
              "on-background": "#0b1c30",
              "surface-container-lowest": "#ffffff",
              "on-secondary-container": "#327015",
              "on-tertiary-container": "#86948b"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "8px",
              "margin": "32px",
              "md": "24px",
              "xs": "4px",
              "gutter": "24px",
              "lg": "48px",
              "sm": "12px",
              "xl": "80px"
      },
      "fontFamily": {
              "label-sm": ["Manrope"],
              "label-md": ["Manrope"],
              "body-md": ["Manrope"],
              "h3": ["Manrope"],
              "body-lg": ["Manrope"],
              "h1": ["Manrope"],
              "h2": ["Manrope"]
      },
      "fontSize": {
              "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
              "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
}